name: sqlite3

version: 0.0.1

description: >-
  Sqlite3 wrapper. Demo for dart:ffi.

author: Daco Harkes <dacoharkes@google.com>, Samir Jindel <sjindel@google.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  test: ^1.5.3
  ffigen: ^0.2.0

ffigen:
  name: SQLite
  description: SQLite bindings.
  output: 'lib/src/third_party/sqlite/sqlite3_bindings_generated.dart'
  headers:
    entry-points:
      - '/usr/include/sqlite3.h'
    include-directives:
      - '**sqlite3.h'
  functions:
    include:
      - sqlite3_close_v2
      - sqlite3_column_count
      - sqlite3_column_decltype
      - sqlite3_column_int
      - sqlite3_column_name
      - sqlite3_column_text
      - sqlite3_column_type
      - sqlite3_errmsg
      - sqlite3_errstr
      - sqlite3_finalize
      - sqlite3_open_v2
      - sqlite3_prepare_v2
      - sqlite3_step
  comments:
    style: any
    length: full
  preamble: |
    // 2001 September 15
    //
    // The author disclaims copyright to this source code.  In place of
    // a legal notice, here is a blessing:
    //
    //    May you do good and not evil.
    //    May you find forgiveness for yourself and forgive others.
    //    May you share freely, never taking more than you give.
